### ISSUE TITLE
Clarify surprises/gotchas + consider adding warnings on readme

### ISSUE THREAD

**Issue by AlbertVilaCalvo** [fabioCollini/DaggerMock#53]
Hi Fabio,

I've been using DaggerMock since yesterday and so far it's been really great - it's awesome to get rid of the boilerplate in such a succinct way.

However, I've encountered 2 surprises.

First, I've noticed that if I don't annotate a field with `@Mock`, the library doesn't mock it. Is this correct? 

I found this because in one test I didn't have to `verify` anything on the mock, so I didn't add the `@Mock` field. But this made the test fail.

If this is the expected behavior, I suggest emphasizing this on the readme so that other people don't get bitten by this. I propose adding something like:

> Note: `DaggerMockRule` will only mock the fields annotated with `@Mock`.

Second, I've also noticed that in order to `verify` something on my mocks, I must delay the launch of the activity by passing `false` to `launchActivity` at the `ActivityTestRule` constructor, like this:
 
```
@Rule public ActivityTestRule<MainActivity> activityRule = new ActivityTestRule<>(MainActivity.class, true, false);
```

Is this correct? If it is, I suggest adding a note on the readme, something like:

> Note: you must manually launch the `Activity` by passing `false` to `launchActivity` at the `ActivityTestRule` constructor.

Yes, I know that this is how it's done on the example on the readme, but still I got bitten by this. It took me like 2 hours to figure out why it didn't work.

If you agree I can send a pull request with these changes.

**Comment by fabioCollini** [comment]
Hi,
thanks for your suggestions and you are right, the documentation should be improved :(
Here's my attempt to clarify that two things:

1. DaggerMock invokes `MockitoAnnotations.initMocks` method and then collects the test fields to use them. If you don't use `@Mock` the field will remain blank but there are cases when you don't want to use that annotation: you can use `@Spy` or just instantiate an object (for example a manually written stub)

1. I always launch the activity manually because I want to define mock behavior at the beginning of the test (before the invocation of the `onCreate` method invocation). Even if you launch the activity at the beginning of the test I prefer to launch it manually, I am not sure about the invocation order of rule code when there are multiple rules defined

**Comment by AlbertVilaCalvo** [comment]
Regarding 1), since I didn't have to verify anything on my mock, I didn't annotate it with `@Mock`. But this made the test use the real presenter (which talked to the real repository...) and made the tests fail. This was unexpected to me and is what I would like to warn about on the readme. Not sure what's the appropriate text we could add though.

Regarding 2), I would explicitly mention on the readme (in the Espresso support section) that you need to launch the activity manually to define behavior and/or verify things on your mocks.

If you are interested on improving this, I can send a pull request. We can discuss the wording there.

**Comment by fabioCollini** [comment]
Hi, I added two notes in the README to clarify these two points. I hope these notes help to understand the DaggerMock behaviour, if you notice something wrong feel free to point it out or create a pull request.
Thanks again for your help

**Comment by AlbertVilaCalvo** [comment]
I've sent a pull request: #56
